apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
        - name: hello-world-service-container
          image: ajres/hello-world-service:ff37c25ef6e47c06a6d0422439dfb268f2a9ae2b
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: "HelloWorldService-${POD_NAME}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name