apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
        - name: hello-world-service-container
          image: ajres/hello-world-service:ad5c2f380575838b0da2f7777096137001ce3a61
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: "HelloWorldService-${POD_NAME}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name