apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-node-port
spec:
  type: NodePort
  selector:
    app: hello-world-service
  ports:
    - protocol: TCP
      port: 80 # Port to expose
      targetPort: 8080 # Port on the pod
      #nodePort: 32575  # NodePort range is typically 30000-32767