name: Change application version in manifest to be deployed on certain environment

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Select service'
        required: true
        type: choice
        options:
          - hello-world-service
      image:
        description: 'Image url from image Registry'
        required: true
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - dev
          - production

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.LOGIN_TOKEN }}

      - name: Print new image value
        run: echo "New image is ${{ github.event.inputs.image }}"

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update image in deployment.yaml
        run: |
          yq -i e '.spec.template.spec.containers[0].image = "${{ github.event.inputs.image }}"' \
            ${{ github.event.inputs.service_name }}/${{ github.event.inputs.environment }}/deployment.yaml

      - name: Commit changes and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.inputs.service_name }}/${{ github.event.inputs.environment }}/deployment.yaml
          git commit -m "Update ${{ github.event.inputs.service_name }}/${{ github.event.inputs.environment }}/deployment.yaml with new image"
          git push
